// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletSICAI.Models;

#nullable disable

namespace WalletSICAI.Migrations
{
    [DbContext(typeof(WalletContext))]
    partial class WalletContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalletSICAI.Models.Administrativo", b =>
                {
                    b.Property<int>("AdministrativoId")
                        .HasColumnType("int")
                        .HasColumnName("AdministrativoID");

                    b.Property<string>("AdministrativoApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdministrativoCedula")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("AdministrativoEmail")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AdministrativoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdministrativoNombreCompleto")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)")
                        .HasComputedColumnSql("(([AdministrativoNombre]+' ')+[AdministrativoApellido])", false);

                    b.Property<byte[]>("AdministrativoPassword")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)");

                    b.Property<byte[]>("AdministrativoSalt")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("AministrativoPuesto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("InstitucionId")
                        .HasColumnType("int")
                        .HasColumnName("InstitucionID");

                    b.HasKey("AdministrativoId")
                        .HasName("PK__Administ__320E52920CDCF077");

                    b.HasIndex("InstitucionId");

                    b.HasIndex(new[] { "AdministrativoCedula" }, "UQ__Administ__91C417C77C0FF3F9")
                        .IsUnique()
                        .HasFilter("[AdministrativoCedula] IS NOT NULL");

                    b.ToTable("Administrativos");
                });

            modelBuilder.Entity("WalletSICAI.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("int")
                        .HasColumnName("EstudianteID");

                    b.Property<string>("EstudianteApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstudianteCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("EstudianteEmailInstitucion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EstudianteEmailPersonal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("EstudianteFechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("EstudianteNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstudianteNombreCompleto")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)")
                        .HasComputedColumnSql("(([EstudianteNombre]+' ')+[EstudianteApellido])", false);

                    b.Property<string>("EstudianteNumeroTelefonico")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("EstudianteSeccion")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<int?>("InstitucionId")
                        .HasColumnType("int")
                        .HasColumnName("InstitucionID");

                    b.Property<int?>("MontoActual")
                        .HasColumnType("int");

                    b.HasKey("EstudianteId")
                        .HasName("PK__Estudian__6F76833800058BCC");

                    b.HasIndex("InstitucionId");

                    b.HasIndex(new[] { "EstudianteCedula" }, "UQ__Estudian__E3012E1D4932A87F")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("WalletSICAI.Models.HistorialRecargaEstudiante", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistorialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialId"));

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int")
                        .HasColumnName("EstudianteID");

                    b.Property<int?>("RecargaId")
                        .HasColumnType("int")
                        .HasColumnName("RecargaID");

                    b.HasKey("HistorialId")
                        .HasName("PK__Historia__975206EF61545E3A");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("RecargaId");

                    b.ToTable("HistorialRecargaEstudiante", (string)null);
                });

            modelBuilder.Entity("WalletSICAI.Models.Institucione", b =>
                {
                    b.Property<int>("InstitucionId")
                        .HasColumnType("int")
                        .HasColumnName("InstitucionID");

                    b.Property<string>("CedulaJuridica")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("InstitucionNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstitucionId")
                        .HasName("PK__Instituc__706D41E993323C46");

                    b.HasIndex(new[] { "CedulaJuridica" }, "UQ__Instituc__024C516541E4417A")
                        .IsUnique();

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("WalletSICAI.Models.Recarga", b =>
                {
                    b.Property<int>("RecargaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecargaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecargaId"));

                    b.Property<int?>("AdministrativoId")
                        .HasColumnType("int")
                        .HasColumnName("AdministrativoID");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int")
                        .HasColumnName("EstudianteID");

                    b.Property<DateOnly?>("FechaRecarga")
                        .HasColumnType("date");

                    b.Property<string>("ModoPagoRecarga")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("MontoRecarga")
                        .HasColumnType("int");

                    b.Property<string>("SolicitanteRecargaApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SolicitanteRecargaCedula")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("SolicitanteRecargaEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SolicitanteRecargaNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SolicitanteRecargaNombreCompleto")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)")
                        .HasComputedColumnSql("(([SolicitanteRecargaNombre]+' ')+[SolicitanteRecargaApellido])", false);

                    b.HasKey("RecargaId")
                        .HasName("PK__Recargas__018A5903E1D95803");

                    b.HasIndex("AdministrativoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Recargas", t =>
                        {
                            t.HasTrigger("trg_AumentoMontoEstudiante");

                            t.HasTrigger("trg_InsertarHistorialRecarga");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WalletSICAI.Models.VwHistorialRecarga", b =>
                {
                    b.Property<string>("AdministrativoNombreCompleto")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)");

                    b.Property<string>("EstudianteCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("EstudianteNombreCompleto")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)");

                    b.Property<DateOnly?>("FechaRecarga")
                        .HasColumnType("date");

                    b.Property<int>("HistorialId")
                        .HasColumnType("int")
                        .HasColumnName("HistorialID");

                    b.Property<int?>("MontoRecarga")
                        .HasColumnType("int");

                    b.Property<string>("SolicitanteRecargaNombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_HistorialRecargas", (string)null);
                });

            modelBuilder.Entity("WalletSICAI.Models.Administrativo", b =>
                {
                    b.HasOne("WalletSICAI.Models.Institucione", "Institucion")
                        .WithMany("Administrativos")
                        .HasForeignKey("InstitucionId")
                        .HasConstraintName("FK_Administrativo_Instititucion");

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("WalletSICAI.Models.Estudiante", b =>
                {
                    b.HasOne("WalletSICAI.Models.Institucione", "Institucion")
                        .WithMany("Estudiantes")
                        .HasForeignKey("InstitucionId")
                        .HasConstraintName("FK_Estudiantes_Institucion");

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("WalletSICAI.Models.HistorialRecargaEstudiante", b =>
                {
                    b.HasOne("WalletSICAI.Models.Estudiante", "Estudiante")
                        .WithMany("HistorialRecargaEstudiantes")
                        .HasForeignKey("EstudianteId")
                        .HasConstraintName("FK_Historial_Estudiante");

                    b.HasOne("WalletSICAI.Models.Recarga", "Recarga")
                        .WithMany("HistorialRecargaEstudiantes")
                        .HasForeignKey("RecargaId")
                        .HasConstraintName("FK_Historial_Recarga");

                    b.Navigation("Estudiante");

                    b.Navigation("Recarga");
                });

            modelBuilder.Entity("WalletSICAI.Models.Recarga", b =>
                {
                    b.HasOne("WalletSICAI.Models.Administrativo", "Administrativo")
                        .WithMany("Recargas")
                        .HasForeignKey("AdministrativoId")
                        .HasConstraintName("FK_Recarga_Administrativo");

                    b.HasOne("WalletSICAI.Models.Estudiante", "Estudiante")
                        .WithMany("Recargas")
                        .HasForeignKey("EstudianteId")
                        .HasConstraintName("FK_Recarga_Estudiante");

                    b.Navigation("Administrativo");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("WalletSICAI.Models.Administrativo", b =>
                {
                    b.Navigation("Recargas");
                });

            modelBuilder.Entity("WalletSICAI.Models.Estudiante", b =>
                {
                    b.Navigation("HistorialRecargaEstudiantes");

                    b.Navigation("Recargas");
                });

            modelBuilder.Entity("WalletSICAI.Models.Institucione", b =>
                {
                    b.Navigation("Administrativos");

                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("WalletSICAI.Models.Recarga", b =>
                {
                    b.Navigation("HistorialRecargaEstudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
